"""
Authoritative canonical family members and recipe catalog.
Provides deterministic, domain-grounded fallbacks for planning and nutrition intelligence.
"""

from backend.app.domain.models import FamilyMember, Recipe
from backend.app.domain.enrichment import enrich_recipe_metadata

CANONICAL_FAMILY_MEMBERS: list[FamilyMember] = [
    FamilyMember(
        id="vikas",
        member_key="vikas",
        name="Vikas",
        marathi_name="विकास",
        age=50,
        sex="male",
        weight_kg=70.0,
        height_cm=171.0,
        activity="Highly active / खूप सक्रिय",
        note="काही डाळ खाल्ल्यानंतर लाल चट्टे येत असल्याची नोंद. ट्रिगर निश्चित होईपर्यंत संशयित डाळ मुद्दाम वाढवू नका.",
        sort_order=0,
    ),
    FamilyMember(
        id="namrata",
        member_key="namrata",
        name="Namrata",
        marathi_name="नम्रता",
        age=40,
        sex="female",
        weight_kg=65.0,
        height_cm=155.0,
        activity="Active household work / घरकामात सक्रिय",
        note="दूध, दही, अंडी, पनीर आणि कडधान्यांची विविधता ठेवा.",
        sort_order=1,
    ),
    FamilyMember(
        id="tejas",
        member_key="tejas",
        name="Tejas",
        marathi_name="तेजस",
        age=14,
        sex="male",
        weight_kg=50.0,
        height_cm=171.0,
        activity="Highly active / खूप सक्रिय",
        note="वाढीचे वय. प्रौढ weight-loss targets वापरू नका. सतत थकवा/वारंवार आजार असल्यास pediatrician.",
        sort_order=2,
    ),
    FamilyMember(
        id="siddhesh",
        member_key="siddhesh",
        name="Siddhesh",
        marathi_name="सिद्धेश",
        age=21,
        sex="male",
        weight_kg=64.0,
        height_cm=182.0,
        activity="Sedentary + calisthenics / बसून काम + व्यायाम",
        note="व्यायामाच्या दिवशी पुरेसे जेवण आणि recovery. Protein powder optional आहे.",
        sort_order=3,
    ),
]

CANONICAL_RECIPES: list[Recipe] = [
    enrich_recipe_metadata(Recipe(
        id="r0",
        recipe_key="r0",
        name="Moong Vegetable Chilla",
        marathi_name="मूग भाजी चिल्ला",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="20 min",
        cooking_method="Stovetop",
        description="Serve with 100–150 g curd per adult portion." if "Serve with 100–150 g curd per adult portion." else None,
        marathi_description=None,
        ingredients=["200 g soaked moong dal", "100 g vegetables", "20 g besan", "ginger, cumin, salt", "10 ml oil"],
        method=["Blend soaked moong with little water.", "Mix vegetables, besan and seasoning.", "Cook 4 medium chillas with measured oil."],
        protein="~11 g",
        fibre="~4 g",
        calories="~220 kcal",
        oil="10 ml",
        note="Serve with 100–150 g curd per adult portion." if "Serve with 100–150 g curd per adult portion." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr38",
        recipe_key="cr38",
        name="Besan vegetable chilla + curd",
        marathi_name="बेसन भाजी चिल्ला + दही",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="15 min",
        cooking_method="Stovetop",
        description="Keep batter medium-thick and cook through." if "Keep batter medium-thick and cook through." else None,
        marathi_description=None,
        ingredients=["160 g besan", "150 g grated carrot, onion and spinach", "400 g plain curd", "ginger, cumin, salt", "10 ml oil"],
        method=["Whisk besan with water and vegetables.", "Cook thin chillas with measured oil.", "Serve with curd."],
        protein="~11 g",
        fibre="~5 g",
        calories="~300 kcal",
        oil="10 ml",
        note="Keep batter medium-thick and cook through." if "Keep batter medium-thick and cook through." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r2",
        recipe_key="r2",
        name="Pesarattu + Peanut Coriander Chutney",
        marathi_name="पेसरट्टू + शेंगदाणा-कोथिंबीर चटणी",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Soak overnight; batch batter." if "Soak overnight; batch batter." else None,
        marathi_description=None,
        ingredients=["240 g soaked whole green gram", "40 g peanuts", "coriander", "ginger, cumin", "10 ml oil"],
        method=["Blend soaked moong.", "Spread thin and cook.", "Blend peanut-coriander chutney."],
        protein="~12 g",
        fibre="~5 g",
        calories="~270 kcal",
        oil="10 ml",
        note="Soak overnight; batch batter." if "Soak overnight; batch batter." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr29",
        recipe_key="cr29",
        name="Ragi dosa + sambar",
        marathi_name="नाचणी डोसा + सांबार",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Fermentation optional; batch batter saves weekday time." if "Fermentation optional; batch batter saves weekday time." else None,
        marathi_description=None,
        ingredients=["160 g ragi flour", "80 g rice flour", "500 g vegetable sambar", "10 ml oil", "cumin, salt"],
        method=["Mix ragi and rice flour with water and rest.", "Spread thin dosas and cook with measured oil.", "Serve with vegetable-rich sambar."],
        protein="~11 g",
        fibre="~6 g",
        calories="~320 kcal",
        oil="10 ml",
        note="Fermentation optional; batch batter saves weekday time." if "Fermentation optional; batch batter saves weekday time." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr33",
        recipe_key="cr33",
        name="Vegetable poha + peanuts + curd",
        marathi_name="भाजी पोहे + शेंगदाणे + दही",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="20 min",
        cooking_method="Stovetop",
        description="Measure peanuts and oil; easy daily breakfast." if "Measure peanuts and oil; easy daily breakfast." else None,
        marathi_description=None,
        ingredients=["240 g poha", "50 g peanuts", "200 g onion, carrot and peas", "400 g plain curd", "10 ml oil", "mustard, cumin, turmeric, lemon, salt"],
        method=["Rinse and drain poha.", "Cook vegetables with tempering.", "Add poha and season.", "Finish with peanuts and serve with curd."],
        protein="~10 g",
        fibre="~5 g",
        calories="~330 kcal",
        oil="10 ml",
        note="Measure peanuts and oil; easy daily breakfast." if "Measure peanuts and oil; easy daily breakfast." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r5",
        recipe_key="r5",
        name="Paneer Bhurji + Roti",
        marathi_name="पनीर भुर्जी + पोळी",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="20 min",
        cooking_method="Stovetop",
        description="Egg-bhurji alternative." if "Egg-bhurji alternative." else None,
        marathi_description=None,
        ingredients=["400 g paneer", "200 g tomato-onion", "8 rotis", "10 ml oil"],
        method=["Cook onion-tomato.", "Add crumbled paneer.", "Serve with rotis."],
        protein="~20 g",
        fibre="~5 g",
        calories="~390 kcal",
        oil="10 ml",
        note="Egg-bhurji alternative." if "Egg-bhurji alternative." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r6",
        recipe_key="r6",
        name="Mixed-Dal Adai",
        marathi_name="मिश्र डाळ अडई",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Use varied dals." if "Use varied dals." else None,
        marathi_description=None,
        ingredients=["250 g mixed dals", "ginger, chilli, curry leaves", "vegetables", "10 ml oil"],
        method=["Soak dals.", "Blend coarse.", "Cook thick pancakes."],
        protein="~13 g",
        fibre="~6 g",
        calories="~300 kcal",
        oil="10 ml",
        note="Use varied dals." if "Use varied dals." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r7",
        recipe_key="r7",
        name="Protein Thalipeeth",
        marathi_name="प्रोटीन थालीपीठ",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Serve with curd." if "Serve with curd." else None,
        marathi_description=None,
        ingredients=["120 g jowar flour", "80 g besan", "40 g ground peanuts", "vegetables"],
        method=["Mix into dough.", "Pat portions.", "Cook with measured oil."],
        protein="~12 g",
        fibre="~6 g",
        calories="~330 kcal",
        oil="15 ml",
        note="Serve with curd." if "Serve with curd." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r8",
        recipe_key="r8",
        name="Matki Usal",
        marathi_name="मटकी उसळ",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Batch-friendly protein anchor." if "Batch-friendly protein anchor." else None,
        marathi_description=None,
        ingredients=["250 g dry matki, sprouted", "200 g tomato-onion", "spices", "10 ml oil"],
        method=["Pressure-cook sprouts.", "Prepare masala.", "Combine and simmer."],
        protein="~13 g",
        fibre="~7 g",
        calories="~280 kcal",
        oil="10 ml",
        note="Batch-friendly protein anchor." if "Batch-friendly protein anchor." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r9",
        recipe_key="r9",
        name="Chole + Roti",
        marathi_name="छोले + पोळी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="35 min",
        cooking_method="Stovetop",
        description="Soak and batch-cook." if "Soak and batch-cook." else None,
        marathi_description=None,
        ingredients=["280 g dry chickpeas", "onion-tomato", "8 rotis", "12 ml oil"],
        method=["Pressure-cook soaked chickpeas.", "Cook masala.", "Simmer together."],
        protein="~15 g",
        fibre="~8 g",
        calories="~390 kcal",
        oil="12 ml",
        note="Soak and batch-cook." if "Soak and batch-cook." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r10",
        recipe_key="r10",
        name="Rajma Masala + Rice",
        marathi_name="राजमा मसाला + भात",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Measure rice portion." if "Measure rice portion." else None,
        marathi_description=None,
        ingredients=["280 g dry rajma", "250 g cooked rice", "onion-tomato", "12 ml oil"],
        method=["Pressure-cook rajma.", "Cook masala.", "Simmer and serve."],
        protein="~14 g",
        fibre="~8 g",
        calories="~430 kcal",
        oil="12 ml",
        note="Measure rice portion." if "Measure rice portion." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r11",
        recipe_key="r11",
        name="Lobia Curry + Roti",
        marathi_name="चवळीची भाजी + पोळी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Rotate with other legumes." if "Rotate with other legumes." else None,
        marathi_description=None,
        ingredients=["250 g dry lobia", "onion-tomato", "8 rotis", "10 ml oil"],
        method=["Pressure-cook lobia.", "Cook masala.", "Combine and serve."],
        protein="~14 g",
        fibre="~8 g",
        calories="~390 kcal",
        oil="10 ml",
        note="Rotate with other legumes." if "Rotate with other legumes." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r12",
        recipe_key="r12",
        name="Palak Paneer",
        marathi_name="पालक पनीर",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Pair with roti and cucumber." if "Pair with roti and cucumber." else None,
        marathi_description=None,
        ingredients=["400 g paneer", "500 g spinach", "tomato, ginger", "12 ml oil"],
        method=["Blanch and blend spinach.", "Cook aromatics.", "Add paneer and spinach."],
        protein="~20 g",
        fibre="~5 g",
        calories="~360 kcal",
        oil="12 ml",
        note="Pair with roti and cucumber." if "Pair with roti and cucumber." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r13",
        recipe_key="r13",
        name="Vegetable Moong Khichdi + Curd",
        marathi_name="भाजी मूग खिचडी + दही",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Comfort meal." if "Comfort meal." else None,
        marathi_description=None,
        ingredients=["180 g rice", "120 g moong dal", "300 g vegetables", "400 g curd"],
        method=["Rinse rice and dal.", "Pressure-cook with vegetables.", "Serve with curd."],
        protein="~12 g",
        fibre="~6 g",
        calories="~350 kcal",
        oil="10 ml",
        note="Comfort meal." if "Comfort meal." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r14",
        recipe_key="r14",
        name="Jowar Bhakri + Matki Usal + Dudhi",
        marathi_name="ज्वारी भाकरी + मटकी उसळ + दुधी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="35 min",
        cooking_method="Stovetop",
        description="Weekend/batch prep." if "Weekend/batch prep." else None,
        marathi_description=None,
        ingredients=["8 jowar bhakri", "700 g matki usal", "500 g dudhi"],
        method=["Prepare bhakri.", "Cook dudhi.", "Serve with usal."],
        protein="~15 g",
        fibre="~9 g",
        calories="~420 kcal",
        oil="10 ml",
        note="Weekend/batch prep." if "Weekend/batch prep." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r15",
        recipe_key="r15",
        name="Matki Misal",
        marathi_name="मटकी मिसळ",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="35 min",
        cooking_method="Stovetop",
        description="Keep farsan measured." if "Keep farsan measured." else None,
        marathi_description=None,
        ingredients=["500 g matki usal", "200 g measured farsan", "4 pav", "onion/coriander"],
        method=["Prepare usal.", "Assemble bowls.", "Serve with measured farsan and pav."],
        protein="~15 g",
        fibre="~9 g",
        calories="~430 kcal",
        oil="12 ml",
        note="Keep farsan measured." if "Keep farsan measured." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r16",
        recipe_key="r16",
        name="Paneer Vegetable Tikka",
        marathi_name="पनीर भाजी टिक्का",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Weekend meal." if "Weekend meal." else None,
        marathi_description=None,
        ingredients=["400 g paneer", "300 g capsicum/onion/tomato", "curd and spices", "10 ml oil"],
        method=["Marinate.", "Skewer/tray-bake.", "Cook until lightly charred."],
        protein="~20 g",
        fibre="~5 g",
        calories="~350 kcal",
        oil="10 ml",
        note="Weekend meal." if "Weekend meal." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr31",
        recipe_key="cr31",
        name="Sprouted moong chaat",
        marathi_name="मोड आलेल्या मूगाची चाट",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="15 min",
        cooking_method="Stovetop",
        description="Do not serve raw sprouts; steam/cook them first." if "Do not serve raw sprouts; steam/cook them first." else None,
        marathi_description=None,
        ingredients=["400 g steamed sprouted moong", "150 g tomato-cucumber", "10 g peanuts", "lemon, coriander", "5 ml oil", "roasted cumin, salt"],
        method=["Steam sprouts until safely cooked.", "Mix with vegetables, peanuts and lemon.", "Season lightly and serve."],
        protein="~9 g",
        fibre="~6 g",
        calories="~180 kcal",
        oil="5 ml",
        note="Do not serve raw sprouts; steam/cook them first." if "Do not serve raw sprouts; steam/cook them first." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r18",
        recipe_key="r18",
        name="Paneer Chaat",
        marathi_name="पनीर चाट",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="10 min",
        cooking_method="Stovetop",
        description="Use fresh safely stored paneer." if "Use fresh safely stored paneer." else None,
        marathi_description=None,
        ingredients=["300 g paneer", "tomato, cucumber, coriander", "lemon and spices"],
        method=["Cube paneer.", "Mix and season."],
        protein="~14 g",
        fibre="~2 g",
        calories="~220 kcal",
        oil="0 ml",
        note="Use fresh safely stored paneer." if "Use fresh safely stored paneer." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="r19",
        recipe_key="r19",
        name="Curd Papaya Flax Bowl",
        marathi_name="दही पपई जवस बाऊल",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="5 min",
        cooking_method="Stovetop",
        description="Keep flax ground and refrigerated." if "Keep flax ground and refrigerated." else None,
        marathi_description=None,
        ingredients=["600 g plain curd", "400 g papaya", "20 g ground flaxseed"],
        method=["Add papaya to curd.", "Top with ground flaxseed."],
        protein="~8 g",
        fibre="~4 g",
        calories="~190 kcal",
        oil="0 ml",
        note="Keep flax ground and refrigerated." if "Keep flax ground and refrigerated." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr52",
        recipe_key="cr52",
        name="Roasted chana + banana",
        marathi_name="भाजलेला हरभरा + केळे",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="3 min",
        cooking_method="Stovetop",
        description="Portable and quick." if "Portable and quick." else None,
        marathi_description=None,
        ingredients=["120 g roasted chana", "4 small bananas"],
        method=["Portion roasted chana.", "Serve one banana per person."],
        protein="~7 g",
        fibre="~5 g",
        calories="~210 kcal",
        oil="0 ml",
        note="Portable and quick." if "Portable and quick." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr9",
        recipe_key="cr9",
        name="Buttermilk + roasted chana",
        marathi_name="ताक + भाजलेला हरभरा",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="5 min",
        cooking_method="Stovetop",
        description="Useful quick afternoon snack, especially in warm weather." if "Useful quick afternoon snack, especially in warm weather." else None,
        marathi_description=None,
        ingredients=["600 ml plain buttermilk", "120 g roasted chana", "cumin, coriander, salt"],
        method=["Whisk buttermilk with cumin and coriander.", "Portion roasted chana.", "Serve chilled or at room temperature."],
        protein="~8 g",
        fibre="~5 g",
        calories="~170 kcal",
        oil="0 ml",
        note="Useful quick afternoon snack, especially in warm weather." if "Useful quick afternoon snack, especially in warm weather." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr11",
        recipe_key="cr11",
        name="Egg bhurji + roti",
        marathi_name="अंडा भुर्जी + पोळी",
        course="Breakfast/Dinner",
        meal_category="Breakfast/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="20 min",
        cooking_method="Stovetop",
        description="Cook eggs fully; egg-free option can be paneer bhurji." if "Cook eggs fully; egg-free option can be paneer bhurji." else None,
        marathi_description=None,
        ingredients=["8 eggs", "8 whole-wheat rotis", "200 g onion-tomato", "100 g spinach", "8 ml oil", "turmeric, cumin, coriander, salt"],
        method=["Whisk eggs.", "Cook onion-tomato and spinach with spices.", "Add eggs and scramble until fully cooked.", "Serve with rotis."],
        protein="~19 g",
        fibre="~4 g",
        calories="~390 kcal",
        oil="8 ml",
        note="Cook eggs fully; egg-free option can be paneer bhurji." if "Cook eggs fully; egg-free option can be paneer bhurji." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr0",
        recipe_key="cr0",
        name="Moong vegetable chilla + curd",
        marathi_name="मूग भाजी चिल्ला + दही",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="20 min",
        cooking_method="Stovetop",
        description="Home-style weekday breakfast; adjust portion for each family member." if "Home-style weekday breakfast; adjust portion for each family member." else None,
        marathi_description=None,
        ingredients=["200 g soaked moong dal", "100 g grated carrot, spinach and onion", "20 g besan", "400 g plain curd", "cumin, ginger, salt", "10 ml oil"],
        method=["Blend soaked moong with a little water.", "Mix vegetables, besan and seasoning into the batter.", "Cook 4 medium chillas with measured oil.", "Serve with plain curd."],
        protein="~12 g",
        fibre="~4 g",
        calories="~280 kcal",
        oil="10 ml",
        note="Home-style weekday breakfast; adjust portion for each family member." if "Home-style weekday breakfast; adjust portion for each family member." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr1",
        recipe_key="cr1",
        name="Moong-paneer chilla",
        marathi_name="मूग-पनीर चिल्ला",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="25 min",
        cooking_method="Stovetop",
        description="Use fresh paneer; keep batter suitable for a soft home-style chilla." if "Use fresh paneer; keep batter suitable for a soft home-style chilla." else None,
        marathi_description=None,
        ingredients=["200 g soaked moong dal", "150 g crumbled paneer", "100 g grated carrot, onion and coriander", "ginger, cumin, salt", "10 ml oil"],
        method=["Blend soaked moong into a thick batter.", "Fold in vegetables and half the paneer.", "Cook 4 chillas with measured oil.", "Top with remaining paneer."],
        protein="~15 g",
        fibre="~4 g",
        calories="~320 kcal",
        oil="10 ml",
        note="Use fresh paneer; keep batter suitable for a soft home-style chilla." if "Use fresh paneer; keep batter suitable for a soft home-style chilla." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr2",
        recipe_key="cr2",
        name="Lobia curry + roti + bhindi + guava",
        marathi_name="चवळीची भाजी + पोळी + भेंडी + पेरू",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Batch-cook lobia on the weekend; keep bhindi lightly cooked." if "Batch-cook lobia on the weekend; keep bhindi lightly cooked." else None,
        marathi_description=None,
        ingredients=["250 g dry lobia, soaked", "8 whole-wheat rotis", "400 g bhindi", "1 guava", "200 g tomato-onion", "12 ml oil", "cumin, turmeric, coriander powder, salt"],
        method=["Pressure-cook soaked lobia until soft.", "Cook tomato-onion masala and simmer lobia.", "Stir-fry sliced bhindi with measured oil.", "Serve with rotis and one guava portion."],
        protein="~17 g",
        fibre="~9 g",
        calories="~500 kcal",
        oil="12 ml",
        note="Batch-cook lobia on the weekend; keep bhindi lightly cooked." if "Batch-cook lobia on the weekend; keep bhindi lightly cooked." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr3",
        recipe_key="cr3",
        name="Roasted chana + guava",
        marathi_name="भाजलेला हरभरा + पेरू",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="5 min",
        cooking_method="Stovetop",
        description="Quick snack; use a smaller or larger portion according to hunger." if "Quick snack; use a smaller or larger portion according to hunger." else None,
        marathi_description=None,
        ingredients=["120 g roasted chana", "2 medium guavas"],
        method=["Portion roasted chana into 4 servings.", "Wash and cut guava.", "Serve together."],
        protein="~8 g",
        fibre="~7 g",
        calories="~210 kcal",
        oil="0 ml",
        note="Quick snack; use a smaller or larger portion according to hunger." if "Quick snack; use a smaller or larger portion according to hunger." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr4",
        recipe_key="cr4",
        name="Paneer vegetable curry + roti + cucumber",
        marathi_name="पनीर भाजी + पोळी + काकडी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Simple home-style curry; avoid overcooking paneer." if "Simple home-style curry; avoid overcooking paneer." else None,
        marathi_description=None,
        ingredients=["400 g paneer", "300 g tomato, onion, capsicum and peas", "8 whole-wheat rotis", "2 cucumbers", "12 ml oil", "ginger, cumin, turmeric, coriander powder, salt"],
        method=["Cook onion, tomato and spices.", "Add chopped vegetables and cook until just tender.", "Add paneer and simmer briefly.", "Serve with rotis and cucumber."],
        protein="~20 g",
        fibre="~6 g",
        calories="~470 kcal",
        oil="12 ml",
        note="Simple home-style curry; avoid overcooking paneer." if "Simple home-style curry; avoid overcooking paneer." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr5",
        recipe_key="cr5",
        name="Chana usal + jowar bhakri + cabbage-carrot koshimbir",
        marathi_name="हरभरा उसळ + ज्वारी भाकरी + कोबी-गाजर कोशिंबीर",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Cook chana thoroughly; keep the koshimbir fresh and lightly seasoned." if "Cook chana thoroughly; keep the koshimbir fresh and lightly seasoned." else None,
        marathi_description=None,
        ingredients=["250 g dry kala chana, soaked", "4 jowar bhakri", "250 g cabbage", "150 g carrot", "lemon, coriander", "200 g tomato-onion", "12 ml oil", "cumin, turmeric, goda masala, salt"],
        method=["Pressure-cook soaked chana until tender.", "Cook tomato-onion masala and simmer chana into usal.", "Prepare cabbage-carrot koshimbir with lemon and coriander.", "Serve with jowar bhakri."],
        protein="~18 g",
        fibre="~11 g",
        calories="~520 kcal",
        oil="12 ml",
        note="Cook chana thoroughly; keep the koshimbir fresh and lightly seasoned." if "Cook chana thoroughly; keep the koshimbir fresh and lightly seasoned." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr6",
        recipe_key="cr6",
        name="Tofu bhurji + roti + tomato-cucumber",
        marathi_name="टोफू भुर्जी + पोळी + टोमॅटो-काकडी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="25 min",
        cooking_method="Stovetop",
        description="A soy-based option without soy-chunk texture." if "A soy-based option without soy-chunk texture." else None,
        marathi_description=None,
        ingredients=["350 g firm tofu, crumbled", "8 whole-wheat rotis", "200 g tomato-onion", "2 cucumbers", "1 tomato", "10 ml oil", "turmeric, cumin, coriander, salt"],
        method=["Press tofu and crumble it.", "Cook onion-tomato masala with spices.", "Add tofu and cook until moisture reduces.", "Serve with rotis and tomato-cucumber."],
        protein="~18 g",
        fibre="~5 g",
        calories="~430 kcal",
        oil="10 ml",
        note="A soy-based option without soy-chunk texture." if "A soy-based option without soy-chunk texture." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr7",
        recipe_key="cr7",
        name="Vegetable uttapam + sambar",
        marathi_name="भाजी उत्तपम + सांबार",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Use fermented dosa batter when available; keep uttapam soft rather than crisp." if "Use fermented dosa batter when available; keep uttapam soft rather than crisp." else None,
        marathi_description=None,
        ingredients=["300 g dosa batter", "150 g finely chopped onion, tomato and capsicum", "500 g vegetable sambar", "10 ml oil", "coriander, cumin, salt"],
        method=["Spread thick uttapam batter on a hot tawa.", "Top with vegetables and cook both sides with measured oil.", "Serve with hot vegetable-rich sambar."],
        protein="~12 g",
        fibre="~6 g",
        calories="~330 kcal",
        oil="10 ml",
        note="Use fermented dosa batter when available; keep uttapam soft rather than crisp." if "Use fermented dosa batter when available; keep uttapam soft rather than crisp." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr8",
        recipe_key="cr8",
        name="Rajma rice + cucumber-onion",
        marathi_name="राजमा भात + काकडी-कांदा",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="45 min",
        cooking_method="Stovetop",
        description="Soak and batch-cook rajma to reduce weekday effort." if "Soak and batch-cook rajma to reduce weekday effort." else None,
        marathi_description=None,
        ingredients=["280 g dry rajma, soaked", "320 g cooked rice", "200 g tomato-onion", "1 cucumber", "1 onion", "12 ml oil", "ginger, cumin, turmeric, coriander powder, salt"],
        method=["Pressure-cook soaked rajma until completely tender.", "Prepare tomato-onion masala and simmer rajma.", "Serve with measured cooked rice.", "Add fresh cucumber-onion on the side."],
        protein="~17 g",
        fibre="~9 g",
        calories="~500 kcal",
        oil="12 ml",
        note="Soak and batch-cook rajma to reduce weekday effort." if "Soak and batch-cook rajma to reduce weekday effort." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr10",
        recipe_key="cr10",
        name="Jowar bhakri + matki usal + cauliflower",
        marathi_name="ज्वारी भाकरी + मटकी उसळ + फुलकोबी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Batch-friendly Maharashtrian-style meal." if "Batch-friendly Maharashtrian-style meal." else None,
        marathi_description=None,
        ingredients=["4 jowar bhakri", "250 g dry matki, sprouted", "400 g cauliflower", "200 g tomato-onion", "12 ml oil", "cumin, turmeric, goda masala, salt"],
        method=["Pressure-cook sprouted matki until tender.", "Cook masala and simmer matki into usal.", "Steam or lightly stir-fry cauliflower.", "Serve with jowar bhakri."],
        protein="~18 g",
        fibre="~10 g",
        calories="~500 kcal",
        oil="12 ml",
        note="Batch-friendly Maharashtrian-style meal." if "Batch-friendly Maharashtrian-style meal." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr12",
        recipe_key="cr12",
        name="Mixed bean curry + roti + dudhi",
        marathi_name="मिश्र कडधान्य भाजी + पोळी + दुधी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Use a mix such as chana, lobia and whole moong; cook thoroughly." if "Use a mix such as chana, lobia and whole moong; cook thoroughly." else None,
        marathi_description=None,
        ingredients=["280 g mixed beans, soaked", "8 whole-wheat rotis", "500 g dudhi", "200 g tomato-onion", "12 ml oil", "cumin, turmeric, coriander powder, salt"],
        method=["Pressure-cook soaked mixed beans until tender.", "Cook tomato-onion masala and simmer beans.", "Cook chopped dudhi until soft.", "Serve with rotis."],
        protein="~18 g",
        fibre="~10 g",
        calories="~500 kcal",
        oil="12 ml",
        note="Use a mix such as chana, lobia and whole moong; cook thoroughly." if "Use a mix such as chana, lobia and whole moong; cook thoroughly." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr13",
        recipe_key="cr13",
        name="Paneer chaat + pomegranate",
        marathi_name="पनीर चाट + डाळिंब",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="10 min",
        cooking_method="Stovetop",
        description="Fresh, quick snack with no deep frying." if "Fresh, quick snack with no deep frying." else None,
        marathi_description=None,
        ingredients=["300 g paneer", "1 pomegranate", "150 g cucumber and tomato", "lemon, coriander", "roasted cumin, salt"],
        method=["Cube paneer and chop vegetables.", "Mix with lemon and spices.", "Top with pomegranate arils."],
        protein="~15 g",
        fibre="~3 g",
        calories="~250 kcal",
        oil="0 ml",
        note="Fresh, quick snack with no deep frying." if "Fresh, quick snack with no deep frying." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr14",
        recipe_key="cr14",
        name="Vegetable moong khichdi + curd + carrot-cucumber",
        marathi_name="भाजी मूग खिचडी + दही + गाजर-काकडी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="35 min",
        cooking_method="Stovetop",
        description="Soft home-style khichdi; easy on busy days." if "Soft home-style khichdi; easy on busy days." else None,
        marathi_description=None,
        ingredients=["180 g rice", "120 g moong dal", "300 g mixed vegetables", "400 g plain curd", "150 g carrot and cucumber", "10 ml oil", "turmeric, cumin, salt"],
        method=["Rinse rice and moong dal.", "Pressure-cook with vegetables, turmeric and water.", "Finish with measured oil tempering if desired.", "Serve with curd statistics and carrot-cucumber."],
        protein="~14 g",
        fibre="~7 g",
        calories="~420 kcal",
        oil="10 ml",
        note="Soft home-style khichdi; easy on busy days." if "Soft home-style khichdi; easy on busy days." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr15",
        recipe_key="cr15",
        name="Besan-paneer chilla",
        marathi_name="बेसन-पनीर चिल्ला",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="20 min",
        cooking_method="Stovetop",
        description="Keep batter medium-thick so it cooks evenly." if "Keep batter medium-thick so it cooks evenly." else None,
        marathi_description=None,
        ingredients=["160 g besan", "150 g paneer", "100 g grated carrot, onion and spinach", "ginger, cumin, salt", "10 ml oil"],
        method=["Whisk besan into a smooth batter.", "Add vegetables and crumbled paneer.", "Cook 4 chillas with measured oil.", "Serve hot."],
        protein="~16 g",
        fibre="~5 g",
        calories="~330 kcal",
        oil="10 ml",
        note="Keep batter medium-thick so it cooks evenly." if "Keep batter medium-thick so it cooks evenly." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr16",
        recipe_key="cr16",
        name="Chole + roti + cabbage-peas + apple",
        marathi_name="छोले + पोळी + कोबी-वाटाणा + सफरचंद",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Home-style chole; keep the vegetable side lightly spiced." if "Home-style chole; keep the vegetable side lightly spiced." else None,
        marathi_description=None,
        ingredients=["280 g dry chickpeas, soaked", "8 whole-wheat rotis", "350 g cabbage", "100 g peas", "1 apple", "200 g tomato-onion", "12 ml oil", "cumin, turmeric, coriander powder, salt"],
        method=["Pressure-cook soaked chickpeas.", "Prepare masala and simmer chole.", "Cook cabbage and peas until just tender.", "Serve with rotis and apple."],
        protein="~18 g",
        fibre="~10 g",
        calories="~520 kcal",
        oil="12 ml",
        note="Home-style chole; keep the vegetable side lightly spiced." if "Home-style chole; keep the vegetable side lightly spiced." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr17",
        recipe_key="cr17",
        name="Milk + banana + peanut powder",
        marathi_name="दूध + केळे + शेंगदाणा पूड",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="5 min",
        cooking_method="Stovetop",
        description="Quick snack; avoid adding sugar routinely." if "Quick snack; avoid adding sugar routinely." else None,
        marathi_description=None,
        ingredients=["600 ml milk", "4 bananas", "40 g roasted peanut powder"],
        method=["Warm or serve milk as preferred.", "Slice one banana per serving.", "Sprinkle measured peanut powder."],
        protein="~10 g",
        fibre="~3 g",
        calories="~250 kcal",
        oil="0 ml",
        note="Quick snack; avoid adding sugar routinely." if "Quick snack; avoid adding sugar routinely." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr18",
        recipe_key="cr18",
        name="Palak paneer + roti + cucumber",
        marathi_name="पालक पनीर + पोळी + काकडी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="35 min",
        cooking_method="Stovetop",
        description="Keep spinach bright and paneer lightly cooked." if "Keep spinach bright and paneer lightly cooked." else None,
        marathi_description=None,
        ingredients=["400 g paneer", "500 g spinach", "8 whole-wheat rotis", "2 cucumbers", "200 g tomato-onion", "12 ml oil", "ginger, cumin, turmeric, salt"],
        method=["Blanch spinach briefly and blend.", "Cook onion-tomato with spices.", "Add spinach and simmer.", "Add paneer and serve with rotis and cucumber."],
        protein="~21 g",
        fibre="~7 g",
        calories="~500 kcal",
        oil="12 ml",
        note="Keep spinach bright and paneer lightly cooked." if "Keep spinach bright and paneer lightly cooked." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr19",
        recipe_key="cr19",
        name="Handvo + curd",
        marathi_name="हांडवो + दही",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="45 min",
        cooking_method="Stovetop",
        description="Use fermented mixed rice-dal batter for traditional texture; weekend-friendly." if "Use fermented mixed rice-dal batter for traditional texture; weekend-friendly." else None,
        marathi_description=None,
        ingredients=["220 g rice and mixed dal handvo batter", "150 g grated dudhi", "400 g plain curd", "ginger, sesame, cumin, salt", "15 ml oil"],
        method=["Mix handvo batter with grated dudhi and seasoning.", "Pour into a thick tawa or oven-safe pan.", "Cook covered until set and browned, turning if needed.", "Serve with curd."],
        protein="~14 g",
        fibre="~5 g",
        calories="~360 kcal",
        oil="15 ml",
        note="Use fermented mixed rice-dal batter for traditional texture; weekend-friendly." if "Use fermented mixed rice-dal batter for traditional texture; weekend-friendly." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr20",
        recipe_key="cr20",
        name="Bharli vangi + jowar bhakri + curd + cucumber",
        marathi_name="भरली वांगी + ज्वारी भाकरी + दही + काकडी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="45 min",
        cooking_method="Stovetop",
        description="Traditional Maharashtrian home-style preparation; keep stuffing moderate." if "Traditional Maharashtrian home-style preparation; keep stuffing moderate." else None,
        marathi_description=None,
        ingredients=["8 small brinjals", "80 g roasted peanut powder", "30 g sesame", "4 jowar bhakri", "400 g curd", "2 cucumbers", "200 g onion-tomato", "15 ml oil", "goda masala, turmeric, coriander, salt"],
        method=["Slit brinjals and fill with peanut-sesame masala.", "Cook covered with measured oil until tender.", "Serve with jowar bhakri and curd.", "Add cucumber on the side."],
        protein="~16 g",
        fibre="~8 g",
        calories="~500 kcal",
        oil="15 ml",
        note="Traditional Maharashtrian home-style preparation; keep stuffing moderate." if "Traditional Maharashtrian home-style preparation; keep stuffing moderate." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr21",
        recipe_key="cr21",
        name="Chana chaat + mosambi",
        marathi_name="हरभरा चाट + मोसंबी",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="10 min",
        cooking_method="Stovetop",
        description="Use fully cooked chana rather than raw sprouts." if "Use fully cooked chana rather than raw sprouts." else None,
        marathi_description=None,
        ingredients=["240 g boiled kala chana", "150 g tomato-cucumber-onion", "2 mosambi", "lemon, coriander", "roasted cumin, salt"],
        method=["Mix cooked chana with chopped vegetables.", "Season with lemon, cumin and coriander.", "Serve with mosambi segments."],
        protein="~8 g",
        fibre="~7 g",
        calories="~220 kcal",
        oil="0 ml",
        note="Use fully cooked chana rather than raw sprouts." if "Use fully cooked chana rather than raw sprouts." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr22",
        recipe_key="cr22",
        name="Soy-paneer keema + roti + cabbage",
        marathi_name="सोया-पनीर कीमा + पोळी + कोबी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Uses minced soy rather than soy chunks for a softer keema texture." if "Uses minced soy rather than soy chunks for a softer keema texture." else None,
        marathi_description=None,
        ingredients=["120 g dry soy granules", "200 g paneer", "8 whole-wheat rotis", "300 g finely chopped cabbage", "200 g tomato-onion", "12 ml oil", "ginger, cumin, turmeric, coriander powder, salt"],
        method=["Soak soy granules in hot water, rinse and squeeze well.", "Cook tomato-onion masala.", "Add minced soy and crumbled paneer; cook until dry.", "Serve with rotis and lightly cooked cabbage."],
        protein="~22 g",
        fibre="~8 g",
        calories="~500 kcal",
        oil="12 ml",
        note="Uses minced soy rather than soy chunks for a softer keema texture." if "Uses minced soy rather than soy chunks for a softer keema texture." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr23",
        recipe_key="cr23",
        name="Methi dashmi + curd + banana",
        marathi_name="मेथी दशमी + दही + केळे",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="35 min",
        cooking_method="Stovetop",
        description="Traditional home-style flatbread; keep oil measured." if "Traditional home-style flatbread; keep oil measured." else None,
        marathi_description=None,
        ingredients=["220 g whole-wheat atta", "80 g besan", "50 g chopped fresh methi", "400 g plain curd", "4 bananas", "12 ml oil", "turmeric, cumin, chilli, salt"],
        method=["Mix atta, besan, methi and spices into a soft dough.", "Roll thin dashmi and cook on a tawa with measured oil.", "Serve with curd and one banana per serving."],
        protein="~13 g",
        fibre="~5 g",
        calories="~380 kcal",
        oil="12 ml",
        note="Traditional home-style flatbread; keep oil measured." if "Traditional home-style flatbread; keep oil measured." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr24",
        recipe_key="cr24",
        name="Matki misal + pav + cucumber-onion",
        marathi_name="मटकी मिसळ + पाव + काकडी-कांदा",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Keep farsan measured; the usal remains the main protein component." if "Keep farsan measured; the usal remains the main protein component." else None,
        marathi_description=None,
        ingredients=["500 g cooked sprouted matki usal", "4 pav", "200 g onion", "1 cucumber", "100 g measured farsan", "200 g tomato-onion masala", "12 ml oil", "lemon, coriander, goda masala, salt"],
        method=["Cook sprouted matki until tender and make a moderately spiced usal.", "Assemble bowls with usal and a measured amount of farsan.", "Serve with pav, cucumber and onion."],
        protein="~18 g",
        fibre="~9 g",
        calories="~500 kcal",
        oil="12 ml",
        note="Keep farsan measured; the usal remains the main protein component." if "Keep farsan measured; the usal remains the main protein component." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr25",
        recipe_key="cr25",
        name="Curd + papaya + flax",
        marathi_name="दही + पपई + जवस",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="5 min",
        cooking_method="Stovetop",
        description="Keep ground flax refrigerated and use fresh curd." if "Keep ground flax refrigerated and use fresh curd." else None,
        marathi_description=None,
        ingredients=["600 g plain curd", "400 g papaya", "20 g ground flaxseed"],
        method=["Cube papaya.", "Add to curd.", "Top with ground flaxseed."],
        protein="~8 g",
        fibre="~5 g",
        calories="~200 kcal",
        oil="0 ml",
        note="Keep ground flax refrigerated and use fresh curd." if "Keep ground flax refrigerated and use fresh curd." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr26",
        recipe_key="cr26",
        name="Paneer vegetable tikka + roti + tomato-cucumber",
        marathi_name="पनीर भाजी टिक्का + पोळी + टोमॅटो-काकडी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="35 min",
        cooking_method="Stovetop",
        description="Home-style tawa/baked tikka; no deep frying." if "Home-style tawa/baked tikka; no deep frying." else None,
        marathi_description=None,
        ingredients=["400 g paneer", "300 g capsicum, onion and tomato", "8 whole-wheat rotis", "200 g tomato-cucumber", "100 g curd", "10 ml oil", "turmeric, cumin, chilli, coriander, salt"],
        method=["Marinate paneer and vegetables in curd and spices.", "Cook on tawa or bake until lightly browned.", "Serve with rotis and fresh tomato-cucumber."],
        protein="~21 g",
        fibre="~6 g",
        calories="~480 kcal",
        oil="10 ml",
        note="Home-style tawa/baked tikka; no deep frying." if "Home-style tawa/baked tikka; no deep frying." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr27",
        recipe_key="cr27",
        name="Peanuts + banana",
        marathi_name="शेंगदाणे + केळे",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="3 min",
        cooking_method="Stovetop",
        description="Simple portable snack; portion peanuts rather than eating from the packet." if "Simple portable snack; portion peanuts rather than eating from the packet." else None,
        marathi_description=None,
        ingredients=["80 g roasted peanuts", "4 bananas"],
        method=["Portion peanuts.", "Serve one banana per person."],
        protein="~8 g",
        fibre="~3 g",
        calories="~220 kcal",
        oil="0 ml",
        note="Simple portable snack; portion peanuts rather than eating from the packet." if "Simple portable snack; portion peanuts rather than eating from the packet." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr28",
        recipe_key="cr28",
        name="Paneer bhurji + roti + spinach",
        marathi_name="पनीर भुर्जी + पोळी + पालक",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="25 min",
        cooking_method="Stovetop",
        description="Fast weekday protein-rich meal." if "Fast weekday protein-rich meal." else None,
        marathi_description=None,
        ingredients=["400 g paneer", "8 whole-wheat rotis", "300 g spinach", "200 g tomato-onion", "10 ml oil", "cumin, turmeric, coriander, salt"],
        method=["Cook tomato-onion masala and crumble in paneer.", "Cook spinach separately with light seasoning.", "Serve bhurji with rotis and spinach."],
        protein="~21 g",
        fibre="~6 g",
        calories="~470 kcal",
        oil="10 ml",
        note="Fast weekday protein-rich meal." if "Fast weekday protein-rich meal." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr30",
        recipe_key="cr30",
        name="Chana usal + roti + cauliflower-carrot",
        marathi_name="हरभरा उसळ + पोळी + फुलकोबी-गाजर",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="A practical weekday variation of chana usal." if "A practical weekday variation of chana usal." else None,
        marathi_description=None,
        ingredients=["250 g dry kala chana, soaked", "8 whole-wheat rotis", "300 g cauliflower", "150 g carrot", "200 g tomato-onion", "12 ml oil", "cumin, turmeric, goda masala, salt"],
        method=["Pressure-cook chana until tender.", "Prepare masala and simmer chana.", "Cook cauliflower and carrot until just tender.", "Serve with rotis."],
        protein="~18 g",
        fibre="~10 g",
        calories="~500 kcal",
        oil="12 ml",
        note="A practical weekday variation of chana usal." if "A practical weekday variation of chana usal." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr32",
        recipe_key="cr32",
        name="Egg bhurji + roti + dudhi",
        marathi_name="अंडा भुर्जी + पोळी + दुधी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Cook eggs fully; keep dudhi soft and lightly seasoned." if "Cook eggs fully; keep dudhi soft and lightly seasoned." else None,
        marathi_description=None,
        ingredients=["8 eggs", "8 whole-wheat rotis", "400 g dudhi", "200 g onion-tomato", "10 ml oil", "cumin, turmeric, coriander, salt"],
        method=["Cook chopped dudhi until tender.", "Cook onion-tomato masala.", "Add beaten eggs and scramble fully.", "Serve with rotis and dudhi."],
        protein="~19 g",
        fibre="~6 g",
        calories="~450 kcal",
        oil="10 ml",
        note="Cook eggs fully; keep dudhi soft and lightly seasoned." if "Cook eggs fully; keep dudhi soft and lightly seasoned." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr34",
        recipe_key="cr34",
        name="Rajma rice + cucumber + papaya",
        marathi_name="राजमा भात + काकडी + पपई",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="45 min",
        cooking_method="Stovetop",
        description="Keep the fruit as a separate simple side portion." if "Keep the fruit as a separate simple side portion." else None,
        marathi_description=None,
        ingredients=["280 g dry rajma, soaked", "320 g cooked rice", "1 cucumber", "300 g papaya", "200 g tomato-onion", "12 ml oil", "ginger, cumin, turmeric, salt"],
        method=["Pressure-cook rajma until completely tender.", "Cook tomato-onion masala and simmer rajma.", "Serve with measured rice.", "Add cucumber and papaya on the side."],
        protein="~17 g",
        fibre="~9 g",
        calories="~520 kcal",
        oil="12 ml",
        note="Keep the fruit as a separate simple side portion." if "Keep the fruit as a separate simple side portion." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr35",
        recipe_key="cr35",
        name="Pesarattu + peanut chutney",
        marathi_name="पेसरट्टू + शेंगदाणा चटणी",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Soak overnight and make batter in batches." if "Soak overnight and make batter in batches." else None,
        marathi_description=None,
        ingredients=["240 g soaked whole green gram", "40 g roasted peanuts", "coriander", "ginger, cumin, lemon, salt", "10 ml oil"],
        method=["Blend soaked moong into a smooth batter.", "Spread thin pesarattu and cook with measured oil.", "Grind peanuts, coriander, lemon and spices into chutney.", "Serve together."],
        protein="~13 g",
        fibre="~5 g",
        calories="~300 kcal",
        oil="10 ml",
        note="Soak overnight and make batter in batches." if "Soak overnight and make batter in batches." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr36",
        recipe_key="cr36",
        name="Mixed bean curry + roti + cabbage-carrot",
        marathi_name="मिश्र कडधान्य भाजी + पोळी + कोबी-गाजर",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Use thoroughly cooked mixed beans." if "Use thoroughly cooked mixed beans." else None,
        marathi_description=None,
        ingredients=["280 g mixed beans, soaked", "8 whole-wheat rotis", "250 g cabbage", "150 g carrot", "200 g tomato-onion", "12 ml oil", "cumin, turmeric, coriander powder, salt"],
        method=["Pressure-cook mixed beans until tender.", "Prepare tomato-onion masala and simmer beans.", "Make a quick cabbage-carrot stir-fry.", "Serve with rotis."],
        protein="~18 g",
        fibre="~11 g",
        calories="~500 kcal",
        oil="12 ml",
        note="Use thoroughly cooked mixed beans." if "Use thoroughly cooked mixed beans." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr37",
        recipe_key="cr37",
        name="Tofu vegetable curry + roti + cucumber",
        marathi_name="टोफू भाजी + पोळी + काकडी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="A soft soy option without chunky soy texture." if "A soft soy option without chunky soy texture." else None,
        marathi_description=None,
        ingredients=["350 g firm tofu", "300 g tomato, onion, capsicum and peas", "8 whole-wheat rotis", "2 cucumbers", "12 ml oil", "ginger, cumin, turmeric, coriander powder, salt"],
        method=["Press and cube tofu.", "Cook tomato-onion masala and vegetables.", "Add tofu and simmer briefly.", "Serve with rotis and cucumber."],
        protein="~18 g",
        fibre="~6 g",
        calories="~470 kcal",
        oil="12 ml",
        note="A soft soy option without chunky soy texture." if "A soft soy option without chunky soy texture." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr39",
        recipe_key="cr39",
        name="Chole + roti + bhindi + apple",
        marathi_name="छोले + पोळी + भेंडी + सफरचंद",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Batch-cook chickpeas to shorten weekday preparation." if "Batch-cook chickpeas to shorten weekday preparation." else None,
        marathi_description=None,
        ingredients=["280 g dry chickpeas, soaked", "8 whole-wheat rotis", "400 g bhindi", "1 apple", "200 g tomato-onion", "12 ml oil", "cumin, turmeric, coriander powder, salt"],
        method=["Pressure-cook chickpeas.", "Prepare masala and simmer chole.", "Cook bhindi with measured oil.", "Serve with rotis and apple."],
        protein="~18 g",
        fibre="~10 g",
        calories="~520 kcal",
        oil="12 ml",
        note="Batch-cook chickpeas to shorten weekday preparation." if "Batch-cook chickpeas to shorten weekday preparation." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr40",
        recipe_key="cr40",
        name="Mixed-dal adai + tomato chutney",
        marathi_name="मिश्र डाळ अडई + टोमॅटो चटणी",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="35 min",
        cooking_method="Stovetop",
        description="Use varied dals; cook the adai thoroughly." if "Use varied dals; cook the adai thoroughly." else None,
        marathi_description=None,
        ingredients=["250 g mixed dals, soaked", "150 g tomato", "ginger, chilli, curry leaves", "100 g vegetables", "10 ml oil", "salt"],
        method=["Soak and coarsely blend mixed dals.", "Mix in vegetables and seasoning.", "Cook thick adai on a tawa with measured oil.", "Cook tomato, ginger and chilli and blend into chutney."],
        protein="~14 g",
        fibre="~6 g",
        calories="~330 kcal",
        oil="10 ml",
        note="Use varied dals; cook the adai thoroughly." if "Use varied dals; cook the adai thoroughly." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr41",
        recipe_key="cr41",
        name="Bharli vangi + jowar bhakri + curd",
        marathi_name="भरली वांगी + ज्वारी भाकरी + दही",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="45 min",
        cooking_method="Stovetop",
        description="Traditional home-style preparation; keep stuffing moderate." if "Traditional home-style preparation; keep stuffing moderate." else None,
        marathi_description=None,
        ingredients=["8 small brinjals", "80 g roasted peanut powder", "30 g sesame", "4 jowar bhakri", "400 g curd", "200 g onion-tomato", "15 ml oil", "goda masala, turmeric, coriander, salt"],
        method=["Fill slit brinjals with peanut-sesame masala.", "Cook covered with measured oil until tender.", "Serve with jowar bhakri and curd."],
        protein="~16 g",
        fibre="~8 g",
        calories="~480 kcal",
        oil="15 ml",
        note="Traditional home-style preparation; keep stuffing moderate." if "Traditional home-style preparation; keep stuffing moderate." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr42",
        recipe_key="cr42",
        name="Protein thalipeeth + curd",
        marathi_name="प्रोटीन थालीपीठ + दही",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Traditional-style mixed flour thalipeeth with added protein foods." if "Traditional-style mixed flour thalipeeth with added protein foods." else None,
        marathi_description=None,
        ingredients=["120 g jowar flour", "80 g besan", "40 g ground peanuts", "150 g grated vegetables", "400 g plain curd", "15 ml oil", "cumin, sesame, salt"],
        method=["Mix flours, peanuts, vegetables and seasoning into a soft dough.", "Pat 4 thalipeeth portions on a tawa.", "Cook with measured oil until both sides are done.", "Serve with curd."],
        protein="~13 g",
        fibre="~6 g",
        calories="~350 kcal",
        oil="15 ml",
        note="Traditional-style mixed flour thalipeeth with added protein foods." if "Traditional-style mixed flour thalipeeth with added protein foods." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr43",
        recipe_key="cr43",
        name="Sprouts poha + curd",
        marathi_name="मोड आलेले पोहे + दही",
        course="Breakfast",
        meal_category="Breakfast",
        meal_role="main",
        servings=4.0,
        time_text="25 min",
        cooking_method="Stovetop",
        description="Cook sprouts before mixing; good for batch-prepped weekday breakfast." if "Cook sprouts before mixing; good for batch-prepped weekday breakfast." else None,
        marathi_description=None,
        ingredients=["180 g poha", "200 g cooked sprouted moong", "150 g onion, carrot and peas", "400 g plain curd", "10 ml oil", "mustard, cumin, turmeric, lemon, salt"],
        method=["Rinse poha.", "Steam or pressure-cook sprouts until tender.", "Cook vegetables and tempering, then add poha and sprouts.", "Serve with curd."],
        protein="~11 g",
        fibre="~6 g",
        calories="~340 kcal",
        oil="10 ml",
        note="Cook sprouts before mixing; good for batch-prepped weekday breakfast." if "Cook sprouts before mixing; good for batch-prepped weekday breakfast." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr44",
        recipe_key="cr44",
        name="Chana usal + jowar bhakri + dudhi",
        marathi_name="हरभरा उसळ + ज्वारी भाकरी + दुधी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Batch-friendly Maharashtrian-style meal." if "Batch-friendly Maharashtrian-style meal." else None,
        marathi_description=None,
        ingredients=["250 g dry kala chana, soaked", "4 jowar bhakri", "500 g dudhi", "200 g tomato-onion", "12 ml oil", "cumin, turmeric, goda masala, salt"],
        method=["Pressure-cook chana until tender.", "Prepare masala and simmer into usal.", "Cook dudhi until soft.", "Serve with jowar bhakri."],
        protein="~18 g",
        fibre="~10 g",
        calories="~500 kcal",
        oil="12 ml",
        note="Batch-friendly Maharashtrian-style meal." if "Batch-friendly Maharashtrian-style meal." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr45",
        recipe_key="cr45",
        name="Curd + banana + pumpkin seeds",
        marathi_name="दही + केळे + भोपळ्याच्या बिया",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="5 min",
        cooking_method="Stovetop",
        description="No added sugar needed for routine use." if "No added sugar needed for routine use." else None,
        marathi_description=None,
        ingredients=["600 g plain curd", "4 bananas", "30 g pumpkin seeds"],
        method=["Slice bananas.", "Divide curd into 4 bowls.", "Top with banana and measured pumpkin seeds."],
        protein="~9 g",
        fibre="~4 g",
        calories="~230 kcal",
        oil="0 ml",
        note="No added sugar needed for routine use." if "No added sugar needed for routine use." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr46",
        recipe_key="cr46",
        name="Tofu bhurji + roti + cucumber-tomato",
        marathi_name="टोफू भुर्जी + पोळी + काकडी-टोमॅटो",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="25 min",
        cooking_method="Stovetop",
        description="Press tofu well for a bhurji-like texture." if "Press tofu well for a bhurji-like texture." else None,
        marathi_description=None,
        ingredients=["350 g firm tofu, crumbled", "8 whole-wheat rotis", "1 cucumber", "2 tomatoes", "200 g onion", "10 ml oil", "turmeric, cumin, coriander, salt"],
        method=["Cook onion and spices.", "Add crumbled tofu and cook until dry.", "Serve with rotis and fresh cucumber-tomato."],
        protein="~18 g",
        fibre="~6 g",
        calories="~440 kcal",
        oil="10 ml",
        note="Press tofu well for a bhurji-like texture." if "Press tofu well for a bhurji-like texture." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr47",
        recipe_key="cr47",
        name="Rajma rice + cabbage-carrot",
        marathi_name="राजमा भात + कोबी-गाजर",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="45 min",
        cooking_method="Stovetop",
        description="A practical vegetable variation of rajma rice." if "A practical vegetable variation of rajma rice." else None,
        marathi_description=None,
        ingredients=["280 g dry rajma, soaked", "320 g cooked rice", "250 g cabbage", "150 g carrot", "200 g tomato-onion", "12 ml oil", "ginger, cumin, turmeric, salt"],
        method=["Pressure-cook rajma until completely tender.", "Cook masala and simmer rajma.", "Stir-fry cabbage and carrot lightly.", "Serve with measured rice."],
        protein="~17 g",
        fibre="~10 g",
        calories="~520 kcal",
        oil="12 ml",
        note="A practical vegetable variation of rajma rice." if "A practical vegetable variation of rajma rice." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr48",
        recipe_key="cr48",
        name="Sprouted moong chaat + cucumber",
        marathi_name="मोड आलेल्या मूगाची चाट + काकडी",
        course="Snack",
        meal_category="Snack",
        meal_role="snack",
        servings=4.0,
        time_text="15 min",
        cooking_method="Stovetop",
        description="Cook sprouts before serving." if "Cook sprouts before serving." else None,
        marathi_description=None,
        ingredients=["400 g steamed sprouted moong", "2 cucumbers", "100 g tomato", "10 g peanuts", "lemon, coriander", "5 ml oil", "roasted cumin, salt"],
        method=["Steam sprouts until cooked.", "Mix with chopped cucumber, tomato and peanuts.", "Season with lemon and cumin."],
        protein="~9 g",
        fibre="~7 g",
        calories="~190 kcal",
        oil="5 ml",
        note="Cook sprouts before serving." if "Cook sprouts before serving." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr49",
        recipe_key="cr49",
        name="Egg bhurji + roti + bhindi",
        marathi_name="अंडा भुर्जी + पोळी + भेंडी",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Cook eggs fully and keep bhindi lightly crisp." if "Cook eggs fully and keep bhindi lightly crisp." else None,
        marathi_description=None,
        ingredients=["8 eggs", "8 whole-wheat rotis", "400 g bhindi", "200 g onion-tomato", "10 ml oil", "cumin, turmeric, coriander, salt"],
        method=["Cook bhindi with measured oil.", "Prepare onion-tomato masala.", "Add beaten eggs and scramble fully.", "Serve with rotis and bhindi."],
        protein="~19 g",
        fibre="~6 g",
        calories="~460 kcal",
        oil="10 ml",
        note="Cook eggs fully and keep bhindi lightly crisp." if "Cook eggs fully and keep bhindi lightly crisp." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr50",
        recipe_key="cr50",
        name="Mixed bean curry + roti + dudhi + apple",
        marathi_name="मिश्र कडधान्य भाजी + पोळी + दुधी + सफरचंद",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Cook mixed beans thoroughly and keep fruit as a separate side." if "Cook mixed beans thoroughly and keep fruit as a separate side." else None,
        marathi_description=None,
        ingredients=["280 g mixed beans, soaked", "8 whole-wheat rotis", "500 g dudhi", "1 apple", "200 g tomato-onion", "12 ml oil", "cumin, turmeric, coriander powder, salt"],
        method=["Pressure-cook mixed beans until tender.", "Cook tomato-onion masala and simmer beans.", "Cook dudhi until soft.", "Serve with rotis and apple."],
        protein="~18 g",
        fibre="~10 g",
        calories="~520 kcal",
        oil="12 ml",
        note="Cook mixed beans thoroughly and keep fruit as a separate side." if "Cook mixed beans thoroughly and keep fruit as a separate side." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr51",
        recipe_key="cr51",
        name="Chole + roti + cauliflower-carrot + papaya",
        marathi_name="छोले + पोळी + फुलकोबी-गाजर + पपई",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Keep papaya as a simple fresh side." if "Keep papaya as a simple fresh side." else None,
        marathi_description=None,
        ingredients=["280 g dry chickpeas, soaked", "8 whole-wheat rotis", "300 g cauliflower", "150 g carrot", "300 g papaya", "200 g tomato-onion", "12 ml oil", "cumin, turmeric, coriander powder, salt"],
        method=["Pressure-cook chickpeas.", "Prepare masala and simmer chole.", "Cook cauliflower and carrot until tender.", "Serve with rotis and papaya."],
        protein="~18 g",
        fibre="~11 g",
        calories="~530 kcal",
        oil="12 ml",
        note="Keep papaya as a simple fresh side." if "Keep papaya as a simple fresh side." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr53",
        recipe_key="cr53",
        name="Soy-paneer keema + roti + cabbage salad",
        marathi_name="सोया-पनीर कीमा + पोळी + कोबी कोशिंबीर",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="30 min",
        cooking_method="Stovetop",
        description="Minced soy gives a softer texture than soy chunks." if "Minced soy gives a softer texture than soy chunks." else None,
        marathi_description=None,
        ingredients=["120 g dry soy granules", "200 g paneer", "8 whole-wheat rotis", "300 g finely shredded cabbage", "200 g tomato-onion", "12 ml oil", "lemon, coriander, cumin, turmeric, salt"],
        method=["Soak soy granules in hot water, rinse and squeeze.", "Cook tomato-onion masala.", "Add minced soy and crumbled paneer and cook until dry.", "Toss cabbage with lemon and coriander and serve with rotis."],
        protein="~22 g",
        fibre="~9 g",
        calories="~510 kcal",
        oil="12 ml",
        note="Minced soy gives a softer texture than soy chunks." if "Minced soy gives a softer texture than soy chunks." else None,
    )),
    enrich_recipe_metadata(Recipe(
        id="cr54",
        recipe_key="cr54",
        name="Matki usal + jowar bhakri + cabbage-carrot koshimbir",
        marathi_name="मटकी उसळ + ज्वारी भाकरी + कोबी-गाजर कोशिंबीर",
        course="Lunch/Dinner",
        meal_category="Lunch/Dinner",
        meal_role="main",
        servings=4.0,
        time_text="40 min",
        cooking_method="Stovetop",
        description="Traditional Maharashtrian-style meal with measured oil." if "Traditional Maharashtrian-style meal with measured oil." else None,
        marathi_description=None,
        ingredients=["250 g dry matki, sprouted", "4 jowar bhakri", "250 g cabbage", "150 g carrot", "200 g tomato-onion", "12 ml oil", "lemon, coriander, cumin, goda masala, salt"],
        method=["Pressure-cook sprouted matki until tender.", "Cook tomato-onion masala and simmer matki.", "Prepare cabbage-carrot koshimbir with lemon and coriander.", "Serve with jowar bhakri."],
        protein="~18 g",
        fibre="~11 g",
        calories="~510 kcal",
        oil="12 ml",
        note="Traditional Maharashtrian-style meal with measured oil." if "Traditional Maharashtrian-style meal with measured oil." else None,
    )),
]
