"""
NFDI-001B Canonical Food Catalog Curation.

Authoritative curated metadata for the 40 canonical ingredients of Kutumb Bhojan,
grounded strictly in:
1. ICMR-NIN Dietary Guidelines for Indians (2024)
2. WHO/FAO Healthy Diet Principles & Food-Based Dietary Guidelines

Every record specifies qualitative nutrition, diversity identity, preparation attributes,
provenance, and metadata status.
No calories, no numeric macro grams, no RDA targets, and no clinical claims.
"""

from typing import Any
from backend.app.domain.taxonomy import validate_ingredient_taxonomy

CANONICAL_40_INGREDIENTS_CURATION: dict[str, dict[str, Any]] = {
    # -------------------------------------------------------------------------
    # 1. Grains & Millets
    # -------------------------------------------------------------------------
    "rice": {
        "canonical_key": "rice",
        "display_name_en": "Rice",
        "display_name_mr": "तांदूळ",
        "food_groups": ["grain"],
        "protein_contribution": "minimal",
        "fibre_contribution": "minimal",
        "carbohydrate_role": "primary",
        "fat_contribution": "minimal",
        "fat_quality": "not_meaningful",
        "grain_identity": "rice",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "poha": {
        "canonical_key": "poha",
        "display_name_en": "Poha",
        "display_name_mr": "पोहे",
        "food_groups": ["grain"],
        "protein_contribution": "minimal",
        "fibre_contribution": "minimal",
        "carbohydrate_role": "primary",
        "fat_contribution": "minimal",
        "fat_quality": "not_meaningful",
        "grain_identity": "poha",
        "whole_grain_or_millet": False,
        "soaking_requirement": "short",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "whole_wheat_flour": {
        "canonical_key": "whole_wheat_flour",
        "display_name_en": "Whole-wheat flour",
        "display_name_mr": "गव्हाचे पीठ",
        "food_groups": ["grain"],
        "protein_contribution": "supporting",
        "fibre_contribution": "meaningful",
        "carbohydrate_role": "primary",
        "fat_contribution": "minimal",
        "fat_quality": "not_meaningful",
        "grain_identity": "wheat",
        "whole_grain_or_millet": True,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "jowar_flour": {
        "canonical_key": "jowar_flour",
        "display_name_en": "Jowar flour",
        "display_name_mr": "ज्वारीचे पीठ",
        "food_groups": ["grain", "millet"],
        "protein_contribution": "supporting",
        "fibre_contribution": "meaningful",
        "carbohydrate_role": "primary",
        "fat_contribution": "minimal",
        "fat_quality": "predominantly_unsaturated",
        "grain_identity": "jowar",
        "whole_grain_or_millet": True,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },

    # -------------------------------------------------------------------------
    # 2. Pulses & Legumes
    # -------------------------------------------------------------------------
    "moong_dal": {
        "canonical_key": "moong_dal",
        "display_name_en": "Moong dal",
        "display_name_mr": "मूग डाळ",
        "food_groups": ["legume_pulse"],
        "protein_contribution": "main",
        "fibre_contribution": "meaningful",
        "carbohydrate_role": "supporting",
        "fat_contribution": "minimal",
        "fat_quality": "predominantly_unsaturated",
        "legume_identity": "moong",
        "whole_grain_or_millet": False,
        "soaking_requirement": "short",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "chickpeas": {
        "canonical_key": "chickpeas",
        "display_name_en": "Chickpeas",
        "display_name_mr": "हरभरा",
        "food_groups": ["legume_pulse"],
        "protein_contribution": "main",
        "fibre_contribution": "meaningful",
        "carbohydrate_role": "supporting",
        "fat_contribution": "minimal",
        "fat_quality": "predominantly_unsaturated",
        "legume_identity": "chana",
        "whole_grain_or_millet": False,
        "soaking_requirement": "overnight",
        "advance_preparation": "soaking",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "rajma": {
        "canonical_key": "rajma",
        "display_name_en": "Rajma",
        "display_name_mr": "राजमा",
        "food_groups": ["legume_pulse"],
        "protein_contribution": "main",
        "fibre_contribution": "meaningful",
        "carbohydrate_role": "supporting",
        "fat_contribution": "minimal",
        "fat_quality": "predominantly_unsaturated",
        "legume_identity": "rajma",
        "whole_grain_or_millet": False,
        "soaking_requirement": "overnight",
        "advance_preparation": "soaking",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "matki": {
        "canonical_key": "matki",
        "display_name_en": "Matki",
        "display_name_mr": "मटकी",
        "food_groups": ["legume_pulse"],
        "protein_contribution": "main",
        "fibre_contribution": "meaningful",
        "carbohydrate_role": "supporting",
        "fat_contribution": "minimal",
        "fat_quality": "predominantly_unsaturated",
        "legume_identity": "matki",
        "whole_grain_or_millet": False,
        "soaking_requirement": "overnight",
        "advance_preparation": "soaking",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "lobia": {
        "canonical_key": "lobia",
        "display_name_en": "Lobia",
        "display_name_mr": "चवळी",
        "food_groups": ["legume_pulse"],
        "protein_contribution": "main",
        "fibre_contribution": "meaningful",
        "carbohydrate_role": "supporting",
        "fat_contribution": "minimal",
        "fat_quality": "predominantly_unsaturated",
        "legume_identity": "lobia",
        "whole_grain_or_millet": False,
        "soaking_requirement": "short",
        "advance_preparation": "soaking",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "besan": {
        "canonical_key": "besan",
        "display_name_en": "Besan",
        "display_name_mr": "बेसन",
        "food_groups": ["legume_pulse"],
        "protein_contribution": "main",
        "fibre_contribution": "meaningful",
        "carbohydrate_role": "supporting",
        "fat_contribution": "minimal",
        "fat_quality": "predominantly_unsaturated",
        "legume_identity": "chana",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "soy_granules": {
        "canonical_key": "soy_granules",
        "display_name_en": "Soy granules",
        "display_name_mr": "सोया ग्रॅन्युल्स",
        "food_groups": ["legume_pulse"],
        "protein_contribution": "main",
        "fibre_contribution": "meaningful",
        "carbohydrate_role": "supporting",
        "fat_contribution": "minimal",
        "fat_quality": "predominantly_unsaturated",
        "legume_identity": "soy",
        "whole_grain_or_millet": False,
        "soaking_requirement": "short",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },

    # -------------------------------------------------------------------------
    # 3. Dairy & Eggs
    # -------------------------------------------------------------------------
    "paneer": {
        "canonical_key": "paneer",
        "display_name_en": "Paneer",
        "display_name_mr": "पनीर",
        "food_groups": ["dairy"],
        "protein_contribution": "main",
        "fibre_contribution": "none",
        "carbohydrate_role": "minimal",
        "fat_contribution": "meaningful",
        "fat_quality": "predominantly_saturated",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "curd": {
        "canonical_key": "curd",
        "display_name_en": "Plain curd",
        "display_name_mr": "साधे दही",
        "food_groups": ["dairy"],
        "protein_contribution": "supporting",
        "fibre_contribution": "none",
        "carbohydrate_role": "minimal",
        "fat_contribution": "supporting",
        "fat_quality": "predominantly_saturated",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "milk": {
        "canonical_key": "milk",
        "display_name_en": "Milk",
        "display_name_mr": "दूध",
        "food_groups": ["dairy"],
        "protein_contribution": "supporting",
        "fibre_contribution": "none",
        "carbohydrate_role": "minimal",
        "fat_contribution": "supporting",
        "fat_quality": "predominantly_saturated",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "egg": {
        "canonical_key": "egg",
        "display_name_en": "Egg",
        "display_name_mr": "अंडे",
        "food_groups": ["egg"],
        "protein_contribution": "main",
        "fibre_contribution": "none",
        "carbohydrate_role": "none",
        "fat_contribution": "supporting",
        "fat_quality": "mixed",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },

    # -------------------------------------------------------------------------
    # 4. Vegetables
    # -------------------------------------------------------------------------
    "spinach": {
        "canonical_key": "spinach",
        "display_name_en": "Spinach",
        "display_name_mr": "पालक",
        "food_groups": ["vegetable"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "minimal",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "vegetable_identity": "spinach",
        "vegetable_category": "leafy_green",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "coriander": {
        "canonical_key": "coriander",
        "display_name_en": "Coriander",
        "display_name_mr": "कोथिंबीर",
        "food_groups": ["vegetable"],
        "protein_contribution": "minimal",
        "fibre_contribution": "minimal",
        "carbohydrate_role": "minimal",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "vegetable_identity": "coriander",
        "vegetable_category": "leafy_green",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "cabbage": {
        "canonical_key": "cabbage",
        "display_name_en": "Cabbage",
        "display_name_mr": "कोबी",
        "food_groups": ["vegetable"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "minimal",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "vegetable_identity": "cabbage",
        "vegetable_category": "cruciferous",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "cauliflower": {
        "canonical_key": "cauliflower",
        "display_name_en": "Cauliflower",
        "display_name_mr": "फुलकोबी",
        "food_groups": ["vegetable"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "minimal",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "vegetable_identity": "cauliflower",
        "vegetable_category": "cruciferous",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "carrot": {
        "canonical_key": "carrot",
        "display_name_en": "Carrot",
        "display_name_mr": "गाजर",
        "food_groups": ["vegetable"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "supporting",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "vegetable_identity": "carrot",
        "vegetable_category": "root_tuber",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "onion": {
        "canonical_key": "onion",
        "display_name_en": "Onion",
        "display_name_mr": "कांदा",
        "food_groups": ["vegetable"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "minimal",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "vegetable_identity": "onion",
        "vegetable_category": "root_tuber",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "tomato": {
        "canonical_key": "tomato",
        "display_name_en": "Tomato",
        "display_name_mr": "टोमॅटो",
        "food_groups": ["vegetable"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "minimal",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "vegetable_identity": "tomato",
        "vegetable_category": "fruit_vegetable",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "cucumber": {
        "canonical_key": "cucumber",
        "display_name_en": "Cucumber",
        "display_name_mr": "काकडी",
        "food_groups": ["vegetable"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "minimal",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "vegetable_identity": "cucumber",
        "vegetable_category": "fruit_vegetable",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "bhindi": {
        "canonical_key": "bhindi",
        "display_name_en": "Okra",
        "display_name_mr": "भेंडी",
        "food_groups": ["vegetable"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "minimal",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "vegetable_identity": "bhindi",
        "vegetable_category": "fruit_vegetable",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "bottle_gourd": {
        "canonical_key": "bottle_gourd",
        "display_name_en": "Bottle gourd",
        "display_name_mr": "दुधी भोपळा",
        "food_groups": ["vegetable"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "minimal",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "vegetable_identity": "bottle_gourd",
        "vegetable_category": "fruit_vegetable",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "brinjal": {
        "canonical_key": "brinjal",
        "display_name_en": "Brinjal",
        "display_name_mr": "वांगी",
        "food_groups": ["vegetable"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "minimal",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "vegetable_identity": "brinjal",
        "vegetable_category": "fruit_vegetable",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },

    # -------------------------------------------------------------------------
    # 5. Fruits
    # -------------------------------------------------------------------------
    "banana": {
        "canonical_key": "banana",
        "display_name_en": "Banana",
        "display_name_mr": "केळे",
        "food_groups": ["fruit"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "primary",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "fruit_identity": "banana",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "apple": {
        "canonical_key": "apple",
        "display_name_en": "Apple",
        "display_name_mr": "सफरचंद",
        "food_groups": ["fruit"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "supporting",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "fruit_identity": "apple",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "guava": {
        "canonical_key": "guava",
        "display_name_en": "Guava",
        "display_name_mr": "पेरू",
        "food_groups": ["fruit"],
        "protein_contribution": "minimal",
        "fibre_contribution": "meaningful",
        "carbohydrate_role": "supporting",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "fruit_identity": "guava",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "papaya": {
        "canonical_key": "papaya",
        "display_name_en": "Papaya",
        "display_name_mr": "पपई",
        "food_groups": ["fruit"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "supporting",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "fruit_identity": "papaya",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "pomegranate": {
        "canonical_key": "pomegranate",
        "display_name_en": "Pomegranate",
        "display_name_mr": "डाळिंब",
        "food_groups": ["fruit"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "supporting",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "fruit_identity": "pomegranate",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "mosambi": {
        "canonical_key": "mosambi",
        "display_name_en": "Sweet lime",
        "display_name_mr": "मोसंबी",
        "food_groups": ["fruit"],
        "protein_contribution": "minimal",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "supporting",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "fruit_identity": "mosambi",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "lemon": {
        "canonical_key": "lemon",
        "display_name_en": "Lemon",
        "display_name_mr": "लिंबू",
        "food_groups": ["fruit"],
        "protein_contribution": "none",
        "fibre_contribution": "minimal",
        "carbohydrate_role": "minimal",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "fruit_identity": "lemon",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },

    # -------------------------------------------------------------------------
    # 6. Nuts & Seeds
    # -------------------------------------------------------------------------
    "peanuts": {
        "canonical_key": "peanuts",
        "display_name_en": "Peanuts",
        "display_name_mr": "शेंगदाणे",
        "food_groups": ["nut_seed", "legume_pulse"],
        "protein_contribution": "supporting",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "minimal",
        "fat_contribution": "meaningful",
        "fat_quality": "predominantly_unsaturated",
        "nut_identity": "peanut",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "flaxseed": {
        "canonical_key": "flaxseed",
        "display_name_en": "Flaxseed",
        "display_name_mr": "जवस",
        "food_groups": ["nut_seed"],
        "protein_contribution": "supporting",
        "fibre_contribution": "meaningful",
        "carbohydrate_role": "minimal",
        "fat_contribution": "meaningful",
        "fat_quality": "predominantly_unsaturated",
        "seed_identity": "flaxseed",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "pumpkin_seeds": {
        "canonical_key": "pumpkin_seeds",
        "display_name_en": "Pumpkin seeds",
        "display_name_mr": "भोपळ्याच्या बिया",
        "food_groups": ["nut_seed"],
        "protein_contribution": "supporting",
        "fibre_contribution": "supporting",
        "carbohydrate_role": "minimal",
        "fat_contribution": "meaningful",
        "fat_quality": "predominantly_unsaturated",
        "seed_identity": "pumpkin_seed",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },

    # -------------------------------------------------------------------------
    # 7. Fats, Spices & Seasonings
    # -------------------------------------------------------------------------
    "oil": {
        "canonical_key": "oil",
        "display_name_en": "Cooking oil",
        "display_name_mr": "खाद्यतेल",
        "food_groups": ["fats_oils"],
        "protein_contribution": "none",
        "fibre_contribution": "none",
        "carbohydrate_role": "none",
        "fat_contribution": "meaningful",
        "fat_quality": "predominantly_unsaturated",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "cumin": {
        "canonical_key": "cumin",
        "display_name_en": "Cumin",
        "display_name_mr": "जिरे",
        "food_groups": ["spices"],
        "protein_contribution": "none",
        "fibre_contribution": "none",
        "carbohydrate_role": "none",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "turmeric": {
        "canonical_key": "turmeric",
        "display_name_en": "Turmeric",
        "display_name_mr": "हळद",
        "food_groups": ["spices"],
        "protein_contribution": "none",
        "fibre_contribution": "none",
        "carbohydrate_role": "none",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
    "salt": {
        "canonical_key": "salt",
        "display_name_en": "Salt",
        "display_name_mr": "मीठ",
        "food_groups": ["seasoning"],
        "protein_contribution": "none",
        "fibre_contribution": "none",
        "carbohydrate_role": "none",
        "fat_contribution": "none",
        "fat_quality": "not_meaningful",
        "whole_grain_or_millet": False,
        "soaking_requirement": "none",
        "advance_preparation": "none",
        "provenance": "icmr_nin_2024",
        "metadata_status": "verified",
    },
}


def validate_all_curated_ingredients() -> list[str]:
    """Validate that every single curated ingredient obeys the controlled taxonomy."""
    errors = []
    for key, data in CANONICAL_40_INGREDIENTS_CURATION.items():
        try:
            validate_ingredient_taxonomy(data)
        except Exception as e:
            errors.append(f"{key}: {e}")
    return errors
