"""
NFDI-001A Representative Food Knowledge Fixtures.

Minimal representative data contract covering:
- legume/pulse
- grain
- millet/whole grain
- leafy vegetable
- root/tuber
- fruit
- seed
- nut
- dairy
- egg
"""

from backend.app.domain.models import CanonicalIngredient

REPRESENTATIVE_INGREDIENTS: tuple[CanonicalIngredient, ...] = (
    CanonicalIngredient(
        id="ing-moong-dal-001",
        canonical_key="moong_dal",
        display_name_en="Moong Dal",
        display_name_mr="मूग डाळ",
        aliases=("Moong", "moong dal", "मूग डाळ", "yellow moong dal", "moong"),
        food_groups=("legume_pulse",),
        protein_contribution="main",
        fibre_contribution="meaningful",
        carbohydrate_role="supporting",
        fat_contribution="minimal",
        fat_quality="predominantly_unsaturated",
        legume_identity="moong",
        whole_grain_or_millet=False,
        soaking_requirement="short",
        advance_preparation="none",
        provenance="authored",
        metadata_status="verified",
    ),
    CanonicalIngredient(
        id="ing-rice-002",
        canonical_key="rice",
        display_name_en="Rice",
        display_name_mr="तांदूळ",
        aliases=("rice", "white rice", "भात", "तांदूळ"),
        food_groups=("grain",),
        protein_contribution="minimal",
        fibre_contribution="minimal",
        carbohydrate_role="primary",
        fat_contribution="minimal",
        fat_quality="not_meaningful",
        grain_identity="rice",
        whole_grain_or_millet=False,
        soaking_requirement="none",
        advance_preparation="none",
        provenance="authored",
        metadata_status="verified",
    ),
    CanonicalIngredient(
        id="ing-jowar-003",
        canonical_key="jowar",
        display_name_en="Jowar",
        display_name_mr="ज्वारी",
        aliases=("jowar", "sorghum", "jowar flour", "ज्वारी"),
        food_groups=("grain", "millet"),
        protein_contribution="supporting",
        fibre_contribution="meaningful",
        carbohydrate_role="primary",
        fat_contribution="minimal",
        fat_quality="predominantly_unsaturated",
        grain_identity="jowar",
        whole_grain_or_millet=True,
        soaking_requirement="none",
        advance_preparation="none",
        provenance="authored",
        metadata_status="verified",
    ),
    CanonicalIngredient(
        id="ing-spinach-004",
        canonical_key="spinach",
        display_name_en="Spinach",
        display_name_mr="पालक",
        aliases=("spinach", "palak", "पालक"),
        food_groups=("vegetable",),
        protein_contribution="minimal",
        fibre_contribution="supporting",
        carbohydrate_role="minimal",
        fat_contribution="minimal",
        fat_quality="not_meaningful",
        vegetable_identity="spinach",
        vegetable_category="leafy_green",
        whole_grain_or_millet=False,
        soaking_requirement="none",
        advance_preparation="none",
        provenance="authored",
        metadata_status="verified",
    ),
    CanonicalIngredient(
        id="ing-carrot-005",
        canonical_key="carrot",
        display_name_en="Carrot",
        display_name_mr="गाजर",
        aliases=("carrot", "carrots", "गाजर"),
        food_groups=("vegetable",),
        protein_contribution="minimal",
        fibre_contribution="supporting",
        carbohydrate_role="supporting",
        fat_contribution="minimal",
        fat_quality="not_meaningful",
        vegetable_identity="carrot",
        vegetable_category="root_tuber",
        whole_grain_or_millet=False,
        soaking_requirement="none",
        advance_preparation="none",
        provenance="authored",
        metadata_status="verified",
    ),
    CanonicalIngredient(
        id="ing-banana-006",
        canonical_key="banana",
        display_name_en="Banana",
        display_name_mr="केळे",
        aliases=("banana", "bananas", "केळी", "केळे"),
        food_groups=("fruit",),
        protein_contribution="minimal",
        fibre_contribution="supporting",
        carbohydrate_role="primary",
        fat_contribution="minimal",
        fat_quality="not_meaningful",
        fruit_identity="banana",
        whole_grain_or_millet=False,
        soaking_requirement="none",
        advance_preparation="none",
        provenance="authored",
        metadata_status="verified",
    ),
    CanonicalIngredient(
        id="ing-sesame-007",
        canonical_key="sesame_seeds",
        display_name_en="Sesame Seeds",
        display_name_mr="तीळ",
        aliases=("sesame", "sesame seeds", "til", "तीळ"),
        food_groups=("nut_seed",),
        protein_contribution="supporting",
        fibre_contribution="supporting",
        carbohydrate_role="minimal",
        fat_contribution="meaningful",
        fat_quality="predominantly_unsaturated",
        seed_identity="sesame",
        whole_grain_or_millet=False,
        soaking_requirement="none",
        advance_preparation="none",
        provenance="authored",
        metadata_status="verified",
    ),
    CanonicalIngredient(
        id="ing-peanut-008",
        canonical_key="peanut",
        display_name_en="Peanut",
        display_name_mr="शेंगदाणे",
        aliases=("peanut", "peanuts", "groundnut", "शेंगदाणे"),
        food_groups=("nut_seed", "legume_pulse"),
        protein_contribution="supporting",
        fibre_contribution="supporting",
        carbohydrate_role="minimal",
        fat_contribution="meaningful",
        fat_quality="predominantly_unsaturated",
        nut_identity="peanut",
        whole_grain_or_millet=False,
        soaking_requirement="none",
        advance_preparation="none",
        provenance="authored",
        metadata_status="verified",
    ),
    CanonicalIngredient(
        id="ing-paneer-009",
        canonical_key="paneer",
        display_name_en="Paneer",
        display_name_mr="पनीर",
        aliases=("paneer", "cottage cheese", "पनीर"),
        food_groups=("dairy",),
        protein_contribution="main",
        fibre_contribution="none",
        carbohydrate_role="minimal",
        fat_contribution="meaningful",
        fat_quality="predominantly_saturated",
        whole_grain_or_millet=False,
        soaking_requirement="none",
        advance_preparation="none",
        provenance="authored",
        metadata_status="verified",
    ),
    CanonicalIngredient(
        id="ing-egg-010",
        canonical_key="egg",
        display_name_en="Egg",
        display_name_mr="अंडे",
        aliases=("egg", "eggs", "अंड", "अंडे", "अंडी"),
        food_groups=("egg",),
        protein_contribution="main",
        fibre_contribution="none",
        carbohydrate_role="none",
        fat_contribution="supporting",
        fat_quality="mixed",
        whole_grain_or_millet=False,
        soaking_requirement="none",
        advance_preparation="none",
        provenance="authored",
        metadata_status="verified",
    ),
)
