-- Migration: NFDI-001C Canonical Food Seasonality & Climate Intelligence
-- Normalized additive table with RLS and ICMR-NIN verified seasonal food knowledge.

create table if not exists public.ingredient_seasonality (
  id uuid primary key default gen_random_uuid(),
  ingredient_key text not null,
  season text not null check (season in ('summer', 'monsoon', 'winter', 'all_season')),
  region text not null default 'maharashtra_western_india',
  availability_status text not null check (availability_status in ('peak', 'available', 'scarce', 'unknown')),
  culinary_suitability text check (culinary_suitability in ('cooling', 'warming', 'digestive', 'neutral', 'unknown')),
  provenance text not null default 'icmr_nin_traditional_knowledge',
  metadata_status text not null default 'verified',
  created_at timestamptz not null default now(),
  unique (ingredient_key, season, region)
);

create index if not exists idx_ingredient_seasonality_key on public.ingredient_seasonality(ingredient_key);
create index if not exists idx_ingredient_seasonality_season on public.ingredient_seasonality(season);

-- RLS Security Policies
alter table public.ingredient_seasonality enable row level security;
drop policy if exists ingredient_seasonality_select_all on public.ingredient_seasonality;
create policy ingredient_seasonality_select_all on public.ingredient_seasonality for select using (true);

-- Authoritative Seasonal Data Population
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('bottle_gourd', 'summer', 'maharashtra_western_india', 'peak', 'cooling', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('bottle_gourd', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('bottle_gourd', 'winter', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('cucumber', 'summer', 'maharashtra_western_india', 'peak', 'cooling', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('cucumber', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('cucumber', 'winter', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('spinach', 'winter', 'maharashtra_western_india', 'peak', 'warming', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('spinach', 'summer', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('spinach', 'monsoon', 'maharashtra_western_india', 'scarce', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('carrot', 'winter', 'maharashtra_western_india', 'peak', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('carrot', 'summer', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('carrot', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('cauliflower', 'winter', 'maharashtra_western_india', 'peak', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('cauliflower', 'summer', 'maharashtra_western_india', 'scarce', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('cauliflower', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('cabbage', 'winter', 'maharashtra_western_india', 'peak', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('cabbage', 'summer', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('cabbage', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('bhindi', 'summer', 'maharashtra_western_india', 'peak', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('bhindi', 'monsoon', 'maharashtra_western_india', 'peak', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('bhindi', 'winter', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('brinjal', 'winter', 'maharashtra_western_india', 'peak', 'warming', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('brinjal', 'summer', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('brinjal', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('onion', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('tomato', 'winter', 'maharashtra_western_india', 'peak', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('tomato', 'summer', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('tomato', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('coriander', 'winter', 'maharashtra_western_india', 'peak', 'digestive', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('coriander', 'summer', 'maharashtra_western_india', 'available', 'cooling', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('coriander', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('whole_wheat_flour', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('rice', 'all_season', 'maharashtra_western_india', 'available', 'digestive', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('poha', 'all_season', 'maharashtra_western_india', 'available', 'digestive', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('jowar_flour', 'winter', 'maharashtra_western_india', 'peak', 'warming', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('jowar_flour', 'summer', 'maharashtra_western_india', 'peak', 'cooling', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('jowar_flour', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('moong_dal', 'all_season', 'maharashtra_western_india', 'available', 'digestive', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('chickpeas', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('besan', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('matki', 'monsoon', 'maharashtra_western_india', 'peak', 'warming', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('matki', 'winter', 'maharashtra_western_india', 'available', 'warming', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('matki', 'summer', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('rajma', 'winter', 'maharashtra_western_india', 'peak', 'warming', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('rajma', 'summer', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('rajma', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('lobia', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('soy_granules', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('guava', 'winter', 'maharashtra_western_india', 'peak', 'digestive', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('guava', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('banana', 'all_season', 'maharashtra_western_india', 'available', 'digestive', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('apple', 'winter', 'maharashtra_western_india', 'peak', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('apple', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('apple', 'summer', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('papaya', 'all_season', 'maharashtra_western_india', 'available', 'digestive', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('pomegranate', 'winter', 'maharashtra_western_india', 'peak', 'cooling', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('pomegranate', 'monsoon', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('pomegranate', 'summer', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('mosambi', 'summer', 'maharashtra_western_india', 'peak', 'cooling', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('mosambi', 'monsoon', 'maharashtra_western_india', 'available', 'cooling', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('mosambi', 'winter', 'maharashtra_western_india', 'available', 'cooling', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('lemon', 'summer', 'maharashtra_western_india', 'peak', 'cooling', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('lemon', 'all_season', 'maharashtra_western_india', 'available', 'digestive', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('curd', 'summer', 'maharashtra_western_india', 'peak', 'cooling', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('curd', 'all_season', 'maharashtra_western_india', 'available', 'digestive', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('milk', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('paneer', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('egg', 'winter', 'maharashtra_western_india', 'peak', 'warming', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('egg', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('peanuts', 'winter', 'maharashtra_western_india', 'peak', 'warming', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('peanuts', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('flaxseed', 'winter', 'maharashtra_western_india', 'peak', 'warming', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('flaxseed', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('pumpkin_seeds', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('oil', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('cumin', 'all_season', 'maharashtra_western_india', 'available', 'digestive', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('turmeric', 'all_season', 'maharashtra_western_india', 'available', 'digestive', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;
insert into public.ingredient_seasonality (ingredient_key, season, region, availability_status, culinary_suitability, provenance, metadata_status) values ('salt', 'all_season', 'maharashtra_western_india', 'available', 'neutral', 'icmr_nin_traditional_knowledge', 'verified') on conflict (ingredient_key, season, region) do update set availability_status = excluded.availability_status, culinary_suitability = excluded.culinary_suitability;